package hqc

import (
	"crypto/sha3"
	"encoding/hex"
	"encoding/json"
	"os"
	"strconv"
	"testing"
)

// TestAccumulated verifies the Go implementation against accumulated hash
// anchors generated by v5.0.0 C. Each iteration:
//  1. Squeeze 48 bytes from SHAKE128 source -> keygen entropy
//  2. Init HQC KAT RNG (SHAKE256(entropy || 0x01)) -> keygen reads from it
//  3. Absorb pk, sk into accumulator
//  4. Squeeze 48 bytes from SHAKE128 source -> encaps entropy
//  5. Init HQC KAT RNG again -> encaps reads from it
//  6. Absorb ct, ss_enc into accumulator
//  7. Decaps(ct, sk) -> absorb ss_dec
//
// Final accumulator squeeze(32) must match the reference hash.
//
// Tiers controlled by GOHQC_ACCUMULATED env var:
//
//	unset or "100"  -> 100 iterations (<1s, default)
//	"1000"          -> 1,000 iterations (~3s)
//	"10000"         -> 10,000 iterations (~30s)
//	"100000"        -> 100,000 iterations (~5 min, pre-release gate)
//
// The 1M tier is reference-only and not executed by Go tests.
func TestAccumulated128(t *testing.T) {
	runAccumulated(t, "hqc-128",
		func(rng *KATRNG) (pk, sk []byte, err error) {
			dk, err := GenerateKeyForTest128(rng)
			if err != nil {
				return nil, nil, err
			}
			return dk.EncapsulationKey().Bytes(), dk.Bytes(), nil
		},
		func(rng *KATRNG, pk []byte) (ct, ssEnc []byte, err error) {
			ek, err := ParseEncapsulationKey128(pk)
			if err != nil {
				return nil, nil, err
			}
			ssEnc, ct = EncapsulateForTest128(ek, rng)
			return ct, ssEnc, nil
		},
		func(sk, ct []byte) (ssDec []byte, err error) {
			dk, err := ParseDecapsulationKey128(sk)
			if err != nil {
				return nil, err
			}
			ssDec, err = dk.Decapsulate(ct)
			dk.Destroy()
			return ssDec, err
		},
	)
}

func TestAccumulated192(t *testing.T) {
	runAccumulated(t, "hqc-192",
		func(rng *KATRNG) (pk, sk []byte, err error) {
			dk, err := GenerateKeyForTest192(rng)
			if err != nil {
				return nil, nil, err
			}
			return dk.EncapsulationKey().Bytes(), dk.Bytes(), nil
		},
		func(rng *KATRNG, pk []byte) (ct, ssEnc []byte, err error) {
			ek, err := ParseEncapsulationKey192(pk)
			if err != nil {
				return nil, nil, err
			}
			ssEnc, ct = EncapsulateForTest192(ek, rng)
			return ct, ssEnc, nil
		},
		func(sk, ct []byte) (ssDec []byte, err error) {
			dk, err := ParseDecapsulationKey192(sk)
			if err != nil {
				return nil, err
			}
			ssDec, err = dk.Decapsulate(ct)
			dk.Destroy()
			return ssDec, err
		},
	)
}

func TestAccumulated256(t *testing.T) {
	runAccumulated(t, "hqc-256",
		func(rng *KATRNG) (pk, sk []byte, err error) {
			dk, err := GenerateKeyForTest256(rng)
			if err != nil {
				return nil, nil, err
			}
			return dk.EncapsulationKey().Bytes(), dk.Bytes(), nil
		},
		func(rng *KATRNG, pk []byte) (ct, ssEnc []byte, err error) {
			ek, err := ParseEncapsulationKey256(pk)
			if err != nil {
				return nil, nil, err
			}
			ssEnc, ct = EncapsulateForTest256(ek, rng)
			return ct, ssEnc, nil
		},
		func(sk, ct []byte) (ssDec []byte, err error) {
			dk, err := ParseDecapsulationKey256(sk)
			if err != nil {
				return nil, err
			}
			ssDec, err = dk.Decapsulate(ct)
			dk.Destroy()
			return ssDec, err
		},
	)
}

type accumulatedFile struct {
	HQC128 accumulatedParamSet `json:"hqc-128"`
	HQC192 accumulatedParamSet `json:"hqc-192"`
	HQC256 accumulatedParamSet `json:"hqc-256"`
}

type accumulatedParamSet struct {
	Hashes map[string]string `json:"hashes"`
}

func runAccumulated(t *testing.T, name string,
	keygen func(*KATRNG) (pk, sk []byte, err error),
	encaps func(*KATRNG, []byte) (ct, ssEnc []byte, err error),
	decaps func(sk, ct []byte) (ssDec []byte, err error),
) {
	t.Helper()

	tier := 100
	if env := os.Getenv("GOHQC_ACCUMULATED"); env != "" {
		n, err := strconv.Atoi(env)
		if err != nil {
			t.Fatalf("GOHQC_ACCUMULATED=%q: %v", env, err)
		}
		tier = n
	}

	// Load reference hashes.
	var af accumulatedFile
	data, err := os.ReadFile("testdata/accumulated.json")
	if err != nil {
		t.Fatalf("read accumulated.json: %v", err)
	}
	if err := json.Unmarshal(data, &af); err != nil {
		t.Fatalf("parse accumulated.json: %v", err)
	}

	var hashes map[string]string
	switch name {
	case "hqc-128":
		hashes = af.HQC128.Hashes
	case "hqc-192":
		hashes = af.HQC192.Hashes
	case "hqc-256":
		hashes = af.HQC256.Hashes
	}

	tierStr := strconv.Itoa(tier)
	wantHex, ok := hashes[tierStr]
	if !ok {
		t.Fatalf("no reference hash for tier %d in %s", tier, name)
	}

	// SHAKE128 entropy source (empty init, finalized, deterministic).
	source := sha3.NewSHAKE128()

	// SHAKE128 accumulator (absorbs all outputs).
	accum := sha3.NewSHAKE128()

	entropy := make([]byte, 48)

	for i := 0; i < tier; i++ {
		// Step 1: squeeze 48 bytes from source -> keygen entropy.
		source.Read(entropy)

		// Step 2: create HQC KAT RNG from entropy, keygen via it.
		keyRNG := NewKATRNG(entropy)
		pk, sk, err := keygen(keyRNG)
		if err != nil {
			t.Fatalf("iter %d: keygen: %v", i, err)
		}

		// Step 3: absorb pk, sk.
		accum.Write(pk)
		accum.Write(sk)

		// Step 4: squeeze 48 bytes from source -> encaps entropy.
		source.Read(entropy)

		// Step 5: create new KAT RNG, encaps via it.
		encRNG := NewKATRNG(entropy)
		ct, ssEnc, err := encaps(encRNG, pk)
		if err != nil {
			t.Fatalf("iter %d: encaps: %v", i, err)
		}

		// Step 6: absorb ct, ss_enc.
		accum.Write(ct)
		accum.Write(ssEnc)

		// Step 7: decaps (no randomness needed).
		ssDec, err := decaps(sk, ct)
		if err != nil {
			t.Fatalf("iter %d: decaps: %v", i, err)
		}

		// Step 8: absorb ss_dec.
		accum.Write(ssDec)
	}

	// Final squeeze: 32 bytes.
	got := make([]byte, 32)
	accum.Read(got)

	gotHex := hex.EncodeToString(got)
	if gotHex != wantHex {
		t.Fatalf("%s tier %d: accumulated hash mismatch\ngot:  %s\nwant: %s",
			name, tier, gotHex, wantHex)
	}

	t.Logf("%s tier %d: PASS (%s)", name, tier, gotHex[:16]+"...")
}
